import { instantMeiliSearch } from "@meilisearch/instant-meilisearch";
import { BaseHit } from "instantsearch.js";
import type { NextPage } from "next";
import Head from "next/head";
import {
  Configure,
  InstantSearch,
  SearchBox,
  useHits,
  UseHitsProps,
  RefinementList,
} from "react-instantsearch-hooks-web";
import styles from "../styles/Home.module.css";
import YouTube from "react-youtube";

interface Item {
  id: string;
  text: string;
  start: number;
  end: number;
  video: string;
}

type Hit = Item & {
  _highlightResult: { [id in keyof Item]: { value: Item[id] } };
  _snippetResult: { [id in keyof Item]: { value: Item[id] } };
  __position: number;
};

const searchClient = instantMeiliSearch("http://localhost:7700");

function Video(props: { video: string; start: number; end: number }) {
  return (
    <YouTube
      videoId={props.video}
      opts={{
        height: "200",
        width: "100%",
        playerVars: {
          // https://developers.google.com/youtube/player_parameters
          modestbranding: 1,
          rel: 0,
          autoplay: 0,
          loop: 1,
          start: props.start,
          end: props.end,
        },
      }}
      loading="lazy"
      onEnd={(e) => {
        // https://developers.google.com/youtube/iframe_api_reference
        const player = e.target;
        player.seekTo(props.start);
        player.pauseVideo();
      }}
    />
  );
}

function CustomHits(props: UseHitsProps) {
  // @ts-ignore
  const { hits } = useHits<Hit>(props);

  return (
    <div className={styles.hits}>
      {hits.map((hit) => (
        <div key={hit.id} className={styles.hit}>
          <Video video={hit.video} start={hit.start} end={hit.end} />
          <h2>🗣 {hit.text}</h2>
        </div>
      ))}
    </div>
  );
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/instantsearch.css@7.3.1/themes/reset-min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/templates/basic_search.css"
        />
      </Head>

      <main className={styles.main}>
        <InstantSearch indexName="speeches" searchClient={searchClient}>
          <Configure hitsPerPage={9} />
          <div className={styles.search}>
            <SearchBox />
            <RefinementList attribute="channel" />
          </div>
          <CustomHits />
        </InstantSearch>
      </main>
    </div>
  );
};

export default Home;
